export const mockAccidentData = [
  {
    id: 1,
    latitude: 8.595,
    longitude: 126.095,
    severity: "critical",
    type: "vehicle_collision",
    description: "Multi-vehicle collision on National Highway",
    barangay: "Anibongan",
    created_at: "2024-02-15T08:30:00Z",
    casualties: 3,
    status: "responding",
  },
  {
    id: 2,
    latitude: 8.597,
    longitude: 126.098,
    severity: "high",
    type: "vehicle_collision",
    description: "Motorcycle accident near market",
    barangay: "Anibongan",
    created_at: "2024-02-15T09:15:00Z",
    casualties: 1,
    status: "responding",
  },
  {
    id: 3,
    latitude: 8.593,
    longitude: 126.092,
    severity: "medium",
    type: "vehicle_collision",
    description: "Minor fender bender",
    barangay: "Anibongan",
    created_at: "2024-02-15T07:45:00Z",
    casualties: 0,
    status: "resolved",
  },

  // Coastal area accidents (Barangay Diatagon)
  {
    id: 4,
    latitude: 8.61,
    longitude: 126.11,
    severity: "critical",
    type: "drowning",
    description: "Drowning incident at beach",
    barangay: "Diatagon",
    created_at: "2024-02-15T10:00:00Z",
    casualties: 2,
    status: "responding",
  },
  {
    id: 5,
    latitude: 8.612,
    longitude: 126.108,
    severity: "high",
    type: "boat_accident",
    description: "Fishing boat capsized",
    barangay: "Diatagon",
    created_at: "2024-02-14T16:30:00Z",
    casualties: 1,
    status: "resolved",
  },

  // Mountain road accidents (Barangay Ganayon)
  {
    id: 6,
    latitude: 8.625,
    longitude: 126.085,
    severity: "high",
    type: "vehicle_collision",
    description: "Truck accident on mountain road",
    barangay: "Ganayon",
    created_at: "2024-02-15T06:00:00Z",
    casualties: 2,
    status: "responding",
  },
  {
    id: 7,
    latitude: 8.628,
    longitude: 126.087,
    severity: "medium",
    type: "landslide",
    description: "Minor landslide blocking road",
    barangay: "Ganayon",
    created_at: "2024-02-14T20:00:00Z",
    casualties: 0,
    status: "responding",
  },

  // Poblacion area (town center)
  {
    id: 8,
    latitude: 8.6301,
    longitude: 126.0933,
    severity: "medium",
    type: "fire",
    description: "House fire in residential area",
    barangay: "Poblacion",
    created_at: "2024-02-15T05:00:00Z",
    casualties: 0,
    status: "resolved",
  },
  {
    id: 9,
    latitude: 8.632,
    longitude: 126.095,
    severity: "low",
    type: "medical_emergency",
    description: "Heart attack patient",
    barangay: "Poblacion",
    created_at: "2024-02-15T11:00:00Z",
    casualties: 0,
    status: "responding",
  },
  {
    id: 10,
    latitude: 8.631,
    longitude: 126.094,
    severity: "medium",
    type: "assault",
    description: "Assault incident reported",
    barangay: "Poblacion",
    created_at: "2024-02-15T03:00:00Z",
    casualties: 1,
    status: "resolved",
  },

  // School zone accidents (Barangay Diegas)
  {
    id: 11,
    latitude: 8.645,
    longitude: 126.105,
    severity: "high",
    type: "vehicle_collision",
    description: "School bus accident",
    barangay: "Diegas",
    created_at: "2024-02-15T07:00:00Z",
    casualties: 4,
    status: "responding",
  },
  {
    id: 12,
    latitude: 8.647,
    longitude: 126.107,
    severity: "low",
    type: "medical_emergency",
    description: "Student injury",
    barangay: "Diegas",
    created_at: "2024-02-15T10:30:00Z",
    casualties: 0,
    status: "responding",
  },

  // Rural area incidents
  {
    id: 13,
    latitude: 8.58,
    longitude: 126.07,
    severity: "medium",
    type: "agricultural_accident",
    description: "Farming equipment accident",
    barangay: "San Isidro",
    created_at: "2024-02-15T12:00:00Z",
    casualties: 1,
    status: "responding",
  },
  {
    id: 14,
    latitude: 8.585,
    longitude: 126.075,
    severity: "low",
    type: "animal_related",
    description: "Snake bite incident",
    barangay: "San Isidro",
    created_at: "2024-02-14T18:00:00Z",
    casualties: 0,
    status: "resolved",
  },

  // Bridge area accidents
  {
    id: 15,
    latitude: 8.62,
    longitude: 126.1,
    severity: "critical",
    type: "vehicle_collision",
    description: "Vehicle fell off bridge",
    barangay: "Payasan",
    created_at: "2024-02-15T04:00:00Z",
    casualties: 3,
    status: "responding",
  },
];

// Accident hotspot zones (areas with high accident frequency)
export const accidentHotspots = [
  {
    name: "National Highway Stretch",
    center: [8.595, 126.095],
    radius: 1000, // meters
    accidentCount: 12,
    severity: "critical",
    commonTypes: ["vehicle_collision", "motorcycle_accident"],
    recommendation: "Install speed bumps and warning signs",
  },
  {
    name: "Coastal Road",
    center: [8.611, 126.109],
    radius: 800,
    accidentCount: 8,
    severity: "high",
    commonTypes: ["drowning", "boat_accident"],
    recommendation: "Add lifeguard stations and warning signs",
  },
  {
    name: "Mountain Pass",
    center: [8.6265, 126.086],
    radius: 600,
    accidentCount: 6,
    severity: "high",
    commonTypes: ["vehicle_collision", "landslide"],
    recommendation: "Improve road conditions and add barriers",
  },
  {
    name: "School Zone",
    center: [8.646, 126.106],
    radius: 500,
    accidentCount: 5,
    severity: "medium",
    commonTypes: ["vehicle_collision", "pedestrian_accident"],
    recommendation: "Add crosswalks and reduce speed limit",
  },
  {
    name: "Town Center",
    center: [8.631, 126.094],
    radius: 700,
    accidentCount: 7,
    severity: "medium",
    commonTypes: ["fire", "medical_emergency", "assault"],
    recommendation: "Increase police/fire station presence",
  },
];

// Statistics summary
export const accidentStatistics = {
  totalAccidents: 15,
  last24Hours: 11,
  last7Days: 15,
  byType: {
    vehicle_collision: 7,
    drowning: 1,
    boat_accident: 1,
    fire: 1,
    medical_emergency: 2,
    assault: 1,
    agricultural_accident: 1,
    animal_related: 1,
    landslide: 1,
  },
  bySeverity: {
    critical: 3,
    high: 4,
    medium: 5,
    low: 3,
  },
  byBarangay: {
    Anibongan: 3,
    Diatagon: 2,
    Ganayon: 2,
    Poblacion: 3,
    Diegas: 2,
    "San Isidro": 2,
    Payasan: 1,
  },
  totalCasualties: 18,
  mostDangerousTime: "06:00-09:00 AM",
  mostDangerousDay: "Monday",
};
